import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatCurrency, formatDate, formatStatus } from "@/lib/formatters";
import { calculateFreightProfitability } from "@/lib/freight-intelligence";

export const dynamic = "force-dynamic";
export default async function FreightIntelligencePage() {
  const [opportunities, equipment] = await Promise.all([
    prisma.freightOpportunity.findMany({ orderBy: { updatedAt: "desc" }, take: 12, include: { equipmentProfile: true } }),
    prisma.equipmentProfile.findFirst({ where: { isActive: true }, orderBy: { updatedAt: "desc" } }),
  ]);
  const active = opportunities.filter((item) => !["REJECTED", "EXPIRED", "CONVERTED"].includes(item.decisionStatus));
  const negotiationCount = opportunities.filter((item) => item.decisionStatus === "NEGOTIATING").length;
  const newCount = opportunities.filter((item) => item.decisionStatus === "NEW").length;
  const reviewCount = opportunities.filter((item) => item.compatibilityStatus === "REVIEW_REQUIRED").length;
  const acceptedCount = opportunities.filter((item) => item.decisionStatus === "ACCEPTED").length;
  const rejectedCount = opportunities.filter((item) => item.decisionStatus === "REJECTED").length;
  const currentDate = new Date();
  const expiringCount = opportunities.filter((item) => item.pickupDate && item.pickupDate >= currentDate && item.pickupDate <= new Date(currentDate.getTime() + 3 * 86400000)).length;
  const averageRate = active.filter((item) => item.offeredRate != null).reduce((sum, item) => sum + item.offeredRate!, 0) / (active.filter((item) => item.offeredRate != null).length || 1);
  const estimates = active.map((item) => calculateFreightProfitability({ rate: item.finalNegotiatedRate ?? item.offeredRate, loadedMiles: item.loadedMiles, deadheadMiles: item.deadheadMiles, repositionMiles: item.repositionMiles, estimatedMpg: item.equipmentProfile?.estimatedMpg, estimatedFuelPrice: item.estimatedFuelPrice, estimatedTolls: item.estimatedTolls, dispatchPercent: item.dispatchPercent ?? item.equipmentProfile?.defaultDispatchPercent, maintenancePerMile: item.maintenancePerMile ?? item.equipmentProfile?.maintenancePerMile, insurancePerWeek: item.equipmentProfile?.insurancePerWeek, paymentPerWeek: item.equipmentProfile?.paymentPerWeek, estimatedOtherExpenses: item.estimatedOtherExpenses }));
  const usableRpm = estimates.filter((estimate) => estimate.effectiveGrossRatePerMile != null);
  const usableProfit = estimates.filter((estimate) => estimate.projectedNetProfit != null);
  const averageEffectiveRpm = usableRpm.length ? usableRpm.reduce((sum, estimate) => sum + estimate.effectiveGrossRatePerMile!, 0) / usableRpm.length : null;
  const averageProjectedProfit = usableProfit.length ? usableProfit.reduce((sum, estimate) => sum + estimate.projectedNetProfit!, 0) / usableProfit.length : null;
  return <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8">
    <header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="brand-kicker">Freight Intelligence</p><h1 className="mt-2 text-2xl font-bold text-[#0a2342]">Pre-booking command center</h1><p className="mt-1 text-sm text-[#6b7c93]">Capture manual load-board opportunities, evaluate the lane, negotiate deliberately, and book only with explicit confirmation.</p></div><div className="flex flex-wrap gap-2"><Link href="/freight-intelligence/opportunities/new" className="btn-primary">New opportunity</Link><Link href="/freight-intelligence/equipment" className="btn-secondary">Equipment profile</Link></div></header>
    <section className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><div className="panel p-5"><p className="text-sm text-[#6b7c93]">Active opportunities</p><p className="mt-2 text-3xl font-semibold">{active.length}</p></div><div className="panel p-5"><p className="text-sm text-[#6b7c93]">New / awaiting decision</p><p className="mt-2 text-3xl font-semibold">{newCount}</p></div><div className="panel p-5"><p className="text-sm text-[#6b7c93]">Equipment review</p><p className="mt-2 text-3xl font-semibold">{reviewCount}</p></div><div className="panel p-5"><p className="text-sm text-[#6b7c93]">Negotiations</p><p className="mt-2 text-3xl font-semibold">{negotiationCount}</p></div><div className="panel p-5"><p className="text-sm text-[#6b7c93]">Accepted / rejected</p><p className="mt-2 text-2xl font-semibold">{acceptedCount} / {rejectedCount}</p></div><div className="panel p-5"><p className="text-sm text-[#6b7c93]">Expiring in 3 days</p><p className="mt-2 text-3xl font-semibold">{expiringCount}</p></div></section>
    <section className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="panel p-5"><p className="text-sm text-[#6b7c93]">Average offered rate</p><p className="mt-2 text-2xl font-semibold">{averageRate ? formatCurrency(averageRate) : "Unavailable"}</p></div><div className="panel p-5"><p className="text-sm text-[#6b7c93]">Average effective RPM</p><p className="mt-2 text-2xl font-semibold">{averageEffectiveRpm == null ? "Unavailable" : formatCurrency(averageEffectiveRpm, true)}</p></div><div className="panel p-5"><p className="text-sm text-[#6b7c93]">Average projected profit</p><p className="mt-2 text-2xl font-semibold">{averageProjectedProfit == null ? "Unavailable" : formatCurrency(averageProjectedProfit, true)}</p></div><div className="panel p-5"><p className="text-sm text-[#6b7c93]">Active equipment</p><p className="mt-2 text-lg font-semibold">{equipment?.name ?? "Not configured"}</p></div></section>
    <section className="panel p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold text-[#0a2342]">Recent opportunities</h2><p className="text-sm text-[#6b7c93]">Every result is an estimate and requires driver confirmation.</p></div><Link href="/freight-intelligence/opportunities" className="text-sm font-semibold text-[#145ea0]">View all</Link></div>{opportunities.length ? <div className="space-y-3">{opportunities.map((item) => <Link key={item.id} href={`/freight-intelligence/opportunities/${item.id}`} className="surface-row flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-[#0a2342]">{item.originCity}, {item.originState} to {item.destinationCity}, {item.destinationState}</p><p className="text-xs text-[#6b7c93]">{formatStatus(item.decisionStatus)} · Pickup {formatDate(item.pickupDate)} · {item.brokerName ?? "Broker not set"}</p></div><strong>{item.offeredRate == null ? "Rate missing" : formatCurrency(item.offeredRate)}</strong></Link>)}</div> : <div className="rounded-lg border border-dashed border-[#c8d5e2] p-8 text-center text-sm text-[#6b7c93]">No opportunities yet. Add a manually captured load-board listing to begin.</div>}</section>
    <p className="mt-6 text-xs text-[#6b7c93]">Equipment compatibility is an operational estimate. Confirm freight dimensions, payload, vehicle ratings, securement, and regulatory requirements before accepting a load.</p>
  </div>;
}
